const det = [
    {'_id':'1',
     'time':'5h ago',
     'length':'Full Time',
     'title':'Senior Software Engineer',
     'country':'United Kingdom',
     'company':'Scoot',
     'image':''
    },
    {'_id':'2',
    'time':'20h ago',
    'length':'Part Time',
    'title':'Haskell and PureScript Dev',
    'country':'United States',
    'company':'Blogr',
    'image':''},
    {'_id':'3',
    'time':'1d ago',
    'length':'Part Time',
    'title':'Midlevel Back End Engineer',
    'country':'Russia',
    'company':'Vector',
    'image':''},
    {'_id':'4',
    'time':'2d ago',
    'length':'Full Time',
    'title':'Senior Application Engineer',
    'country':'Japan',
    'company':'Office Lite',
    'image':''},
    {'_id':'5',
    'time':'2d ago',
    'length':'Part Time',
    'title':'Remote DevOps Engineer',
    'country':'Thailand',
    'company':'Pod',
    'image':''},
    {'_id':'6',
    'time':'4d ago',
    'length':'Part Time',
    'title':'Desktop Support Manager',
    'country':'Germany',
    'company':'Creative',
    'image':''},
    {'_id':'7',
    'time':'1w ago',
    'length':'Full Time',
    'title':'iOS Engineer',
    'country':'United States',
    'company':'Pomodoro',
    'image':''},
    {'_id':'8',
    'time':'1w ago',
    'length':'Full Time',
    'title':'Senior EJB Developer',
    'country':'United Kingdom',
    'company':'Maker',
    'image':''},
    {'_id':'9',
    'time':'1w ago',
    'length':'Part Time',
    'title':'Senior Frontend Developer',
    'country':'Singapore',
    'company':'Coffeeroasters',
    'image':''},
    {'_id':'10',
    'time':'2w ago',
    'length':'Freelance',
    'title':'App & Website Designer',
    'country':'United States',
    'company':'Mastercraft',
    'image':''},
    {'_id':'11',
    'time':'1mo ago',
    'length':'Part Time',
    'title':'Fullstack Developer',
    'country':'New Zealand',
    'company':'Crowdfund',
    'image':''},
    {'_id':'12',
    'time':'4d ago',
    'length':'Part Time',
    'title':'Technical Lead Engineer',
    'country':'United Kingdom',
    'company':'Typemaster',
    'image':''}

]

export default det